# Generated by Django 5.2.17 on 2026-10-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_author_category_alter_livro_autor_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='mul_autor',
            field=models.ManyToManyField(related_name='books2', to='biblioteca.author'),
        ),
    ]
