# Generated by Django 5.2.17 on 2026-10-10 18:31

from django.db import migrations

def copiar_autores(apps, schema_editor):
    livros = apps.get_model("biblioteca", "Livro")
    
    for livro in livros.objects.all():
        livro.mul_autor.add(livro.autor)
    
class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_livro_mul_autor'),
    ]

    operations = [
        migrations.RunPython(copiar_autores),
    ]
